package main

import (
	"database/sql"
	"encoding/json"
	"fmt"
	_ "github.com/go-sql-driver/mysql"
	"io/ioutil"
	"net/http"
)

type AutoGenerated1 struct {
	Data struct {
		FansList []struct {
			UID      string `json:"uid"`
			Nickname string `json:"nickname"`
		} `json:"fans_list"`
	} `json:"data"`
}

func main() {
	//timestamp :=int32(time.Now().Unix())//获取当前时间戳
	sign := "d49ae6ff5afc3a87be478f2175b409a0"
	url := fmt.Sprintf("https://open.lmbang.com/user-fans/index?v=4&mvc=1&uid=1&p=1&sign=%v", sign)
	client := &http.Client{}                   //导入请求的包
	req, _ := http.NewRequest("GET", url, nil) //开始请求

	//req.Header.Add("User-Agent","zidingyi")  //自定义表头
	req.Header.Set("Cookie", "LMB_AUTH_CODE=3da2ae424bf460aba6a2b4f8d8640d94; t_skey=3da2ae424bf460aba6a2b4f8d8640d94; __TOKEN_NEW=SESS_09c8bJoxuQHWDpIzcaUQaeLu%2BHs%2FF%2F93Sw4OCU5CIX4jgMrfITEpqihcyoYwtQgWFrqrLaNahEZ5GSqOprd3%2Byf3J2cYP0MKf5rqJiNZlfWOeo6w%2BSYaAg")
	req.Header.Set("Host", "open.lmbang.com")

	resp, _ := client.Do(req) //处理请求
	//defer resp.Body.Close()      //关闭
	body, err := ioutil.ReadAll(resp.Body) //读取响应
	if err != nil {
		fmt.Println(err)
	}
	var tem AutoGenerated1     //用结构体
	json.Unmarshal(body, &tem) //将查到的数据放到结构体中
	//fmt.Println(string(body))    //打印body内数据
	//fmt.Println(tem)				//打印tem内数据
	//fmt.Println(tem.Data.FansList[0].Nickname)   //打印tem中的第一个数据
	save1(tem)
	//remaxid,_=strconv.Atoi(tem.Data.FansList[len(tem.Data.FansList)-1].Id)
}

func save1(userlist2 AutoGenerated1) {
	db, err := sql.Open("mysql", "root:haosql@tcp(127.0.0.1:3306)/test?charset=utf8") //链接数据库
	if err != nil {
		fmt.Printf("open error")
	} else {
		fmt.Printf("open success")
	}
	stmt, err := db.Prepare("INSERT re (mane_id,name) values (?,?)") //插入语句   字段不能填错
	if err != nil {
		fmt.Printf(err.Error())
	}
	for i := 0; i < len(userlist2.Data.FansList); i++ { //循环插入
		_, err := stmt.Exec(userlist2.Data.FansList[i].UID, userlist2.Data.FansList[i].Nickname) //执行数据存储
		if err != nil {
			continue
		}
		fmt.Println(userlist2.Data.FansList[i].UID, userlist2.Data.FansList[i].Nickname)
	}
	db.Close()
}
