package main

import (
	"database/sql"
	"encoding/json"
	"fmt"
	_ "github.com/go-sql-driver/mysql"
	"io/ioutil"
	"net/http"
	"strings"
)

type AutoGenerated4 struct {
	Data []struct {
		ID       string `json:"_id"`
		Nickname string `json:"nickname"`
		Gender   int    `json:"gender"`
	} `json:"data"`
}

func main() {
	url := "https://api.appweimo.com/user/blindDatelist"
	payload := strings.NewReader("location=112.90737%27.85632&type=3&offset=0")
	req, _ := http.NewRequest("POST", url, payload)
	req.Header.Add("Content-type", "application/x-www-form-urlencoded")
	req.Header.Add("Authorization", "Bearer c0b6qzLbAq7oAPD9Zeee46mD2Howzrb09uvwn1LS03zsSOsvE4iop-2h6iDXLAVesgg2FAI")
	req.Header.Add("Accept-encoding", "gzip")
	req.Header.Add("Content-length", "63")
	req.Header.Add("Host", "<calculated when request is sent>")
	req.Header.Add("User-agent", "okhttp/3.12.0")
	res, _ := http.DefaultClient.Do(req)
	//defer res.Body.Close()
	body, _ := ioutil.ReadAll(res.Body)
	var tem AutoGenerated4     //用结构体
	json.Unmarshal(body, &tem) //将查到的数据放到结构体中
	fmt.Println(tem)
	save4(tem)
}

func save4(userlist4 AutoGenerated4) {
	db, err := sql.Open("mysql", "root:haosql@tcp(127.0.0.1:3306)/blogdb?charset=utf8") //链接数据库
	if err != nil {
		fmt.Printf("open error")
	} else {
		fmt.Printf("open success\n")
	}
	stmt, err := db.Prepare("INSERT weimo (nid,nameid,sex) values (?,?,?)") //插入语句   字段不能填错
	if err != nil {
		fmt.Printf(err.Error())
	}
	for i := 0; i < len(userlist4.Data); i++ { //循环插入
		_, err := stmt.Exec(userlist4.Data[i].ID, userlist4.Data[i].Nickname, userlist4.Data[i].Gender) //执行数据存储
		if err != nil {
			continue
		}
		fmt.Println(userlist4.Data[i].ID, userlist4.Data[i].Nickname, userlist4.Data[i].Gender)
	}
	db.Close()
}
